name: Build & Push Docker image

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "app/**"
      - ".github/workflows/docker.yml"

env:
  IMAGE_NAME: timuser91/myapp
  VERSION_TAG: "1.1"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify secrets present
        run: |
          test -n "${{ secrets.DOCKERHUB_USERNAME }}" || (echo "Missing DOCKERHUB_USERNAME" && exit 1)
          test -n "${{ secrets.DOCKERHUB_TOKEN }}" || (echo "Missing DOCKERHUB_TOKEN" && exit 1)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # If your Dockerfile is in repo root, keep this.
      # If it's in ./app, change:  docker build -t $IMAGE_NAME:$VERSION_TAG ./app
      - name: Build (plain docker)
        run: |
          docker --version
          docker build -t $IMAGE_NAME:$VERSION_TAG .

      - name: Tag with short SHA
        run: |
          SHA_TAG=${GITHUB_SHA::12}
          docker tag $IMAGE_NAME:$VERSION_TAG $IMAGE_NAME:$SHA_TAG
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_OUTPUT

      - name: Push both tags
        run: |
          docker push $IMAGE_NAME:$VERSION_TAG
          docker push $IMAGE_NAME:${GITHUB_SHA::12}
